# Generated by Django 3.0 on 2020-11-30 13:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.NullBooleanField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
