# Generated by Django 3.0 on 2020-12-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201202_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.NullBooleanField(choices=[(True, 'female'), (False, 'male'), (None, 'null')]),
        ),
    ]
