# Generated by Django 3.0 on 2020-12-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201202_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.TextField(max_length=300),
        ),
    ]
