# Generated by Django 3.0 on 2020-12-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201213_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='id',
            new_name='id_auto',
        ),
    ]
